from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .animation_ir import build_animation_ir
from .human21_profile import CORE_BONE_COUNT, HUMAN21_BONES, skeleton_profile_metadata, validate_human21_bind_geometry


class MayaPreviewError(ValueError):
    pass


def _reduce_ir(ir: dict[str, Any]) -> dict[str, Any]:
    tracks = []
    for t in ir["tracks"]:
        if int(t["bone_index"]) >= CORE_BONE_COUNT:
            continue
        tracks.append({
            "bone_index": int(t["bone_index"]),
            "flags": int(t["flags"]),
            "position_animated": bool(t["position_animated"]),
            "rotation_animated": bool(t["rotation_animated"]),
            "samples": t["samples"],
        })
    return {
        "schema": ir["schema"],
        "source_path": ir["source_path"],
        "kind": ir["kind"],
        "frame_count": ir["frame_count"],
        "key_count": ir["key_count"],
        "key_times": ir["key_times"],
        "bone_count": ir["bone_count"],
        "tracks": tracks,
    }


def build_maya_preview_script(
    bind_ir: dict[str, Any],
    animation_ir: dict[str, Any],
    unit_scale: float = 100.0,
) -> str:
    bind_src = bind_ir.get("source_path", "<unknown bind source>")
    anim_src = animation_ir.get("source_path", "<unknown animation source>")
    if bind_ir.get("bone_count") != 21:
        raise MayaPreviewError(
            f"Bind/static pose must have 21 bones; got {bind_ir.get('bone_count')} from: {bind_src}"
        )
    if animation_ir.get("bone_count") != 21:
        raise MayaPreviewError(
            f"Animation must have 21 bones; got {animation_ir.get('bone_count')} from: {anim_src}"
        )
    if bind_ir.get("kind") not in ("Static / Pose-like", "Bind Pose-like"):
        raise MayaPreviewError(
            f"Selected bind file is not a bind/static pose. Got {bind_ir.get('kind')!r} from: {bind_src}"
        )
    if animation_ir.get("kind") != "Animation-like":
        raise MayaPreviewError(
            f"Selected animation is not Animation-like. Got {animation_ir.get('kind')!r} from: {anim_src}"
        )

    bind_validation = validate_human21_bind_geometry(bind_ir)
    profile = skeleton_profile_metadata()
    bones = HUMAN21_BONES[:CORE_BONE_COUNT]
    bind_small = _reduce_ir(bind_ir)
    anim_small = _reduce_ir(animation_ir)

    payload = {
        "profile": profile,
        "bind_validation": bind_validation,
        "bind": bind_small,
        "animation": anim_small,
        "unit_scale": float(unit_scale),
    }
    packed = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)

    return f'''# Auto-generated by SecondSightRE.
# Human21 preview: indices 0..18 use a high-confidence provisional topology.
# Second Sight indices 19 and 20 are intentionally omitted until their parents/names are proven.
# Raw axis convention is preserved. Default unit scale is {float(unit_scale):g} (meters-like -> Maya centimeters).

import json
import math
import maya.cmds as cmds
import maya.api.OpenMaya as om

DATA = json.loads(r"""{packed}""")
UNIT_SCALE = float(DATA["unit_scale"])
ROOT_GROUP_NAME = "SecondSight_Human21_Preview"


def _unique(name):
    if not cmds.objExists(name):
        return name
    i = 1
    while cmds.objExists(f"{{name}}_{{i:02d}}"):
        i += 1
    return f"{{name}}_{{i:02d}}"


def _quat_to_euler_deg(q):
    mq = om.MQuaternion(float(q[0]), float(q[1]), float(q[2]), float(q[3]))
    mq.normalizeIt()
    e = mq.asEulerRotation()
    return [math.degrees(e.x), math.degrees(e.y), math.degrees(e.z)]


def _continuous_quat(q, prev):
    q = [float(x) for x in q]
    if prev is not None:
        dot = sum(prev[i] * q[i] for i in range(4))
        if dot < 0.0:
            q = [-x for x in q]
    return q


def _set_local_tr(joint, pos, quat):
    p = [float(x) * UNIT_SCALE for x in pos]
    r = _quat_to_euler_deg(quat)
    cmds.setAttr(joint + ".translate", p[0], p[1], p[2], type="double3")
    cmds.setAttr(joint + ".rotate", r[0], r[1], r[2], type="double3")
    cmds.setAttr(joint + ".jointOrient", 0.0, 0.0, 0.0, type="double3")


def build_preview():
    group = cmds.group(em=True, name=_unique(ROOT_GROUP_NAME))
    cmds.addAttr(group, longName="SecondSightProfile", dataType="string")
    cmds.setAttr(group + ".SecondSightProfile", DATA["profile"]["name"], type="string")
    cmds.addAttr(group, longName="SecondSightSourceAnimation", dataType="string")
    cmds.setAttr(group + ".SecondSightSourceAnimation", DATA["animation"]["source_path"], type="string")

    bind_tracks = {{int(t["bone_index"]): t for t in DATA["bind"]["tracks"]}}
    joints = {{}}

    for bone in DATA["profile"]["bones"][:{CORE_BONE_COUNT}]:
        idx = int(bone["index"])
        name = "SS_" + bone["name"]
        joint = cmds.createNode("joint", name=_unique(name))
        parent = bone["parent"]
        if parent is None:
            cmds.parent(joint, group, relative=True)
        else:
            cmds.parent(joint, joints[int(parent)], relative=True)

        sample = bind_tracks[idx]["samples"][0]
        _set_local_tr(joint, sample["position"], sample["rotation"])
        joints[idx] = joint

    anim_tracks = {{int(t["bone_index"]): t for t in DATA["animation"]["tracks"]}}
    key_times = [float(x) for x in DATA["animation"]["key_times"]]

    for idx in range({CORE_BONE_COUNT}):
        track = anim_tracks[idx]
        joint = joints[idx]
        prev_q = None

        for sample in track["samples"]:
            t = float(sample["time"])
            q = _continuous_quat(sample["rotation"], prev_q)
            prev_q = q

            p = [float(x) * UNIT_SCALE for x in sample["position"]]
            r = _quat_to_euler_deg(q)

            if idx == 0 or track["position_animated"]:
                cmds.setAttr(joint + ".translate", p[0], p[1], p[2], type="double3")
                for attr in ("translateX", "translateY", "translateZ"):
                    cmds.setKeyframe(joint, attribute=attr, time=t)

            cmds.setAttr(joint + ".rotate", r[0], r[1], r[2], type="double3")
            for attr in ("rotateX", "rotateY", "rotateZ"):
                cmds.setKeyframe(joint, attribute=attr, time=t)

        try:
            cmds.filterCurve(joint + ".rotateX", joint + ".rotateY", joint + ".rotateZ")
        except Exception:
            pass

    if key_times:
        cmds.playbackOptions(minTime=min(key_times), maxTime=max(key_times))
        cmds.currentTime(min(key_times), edit=True)

    cmds.select(joints[0], replace=True)
    print("SecondSightRE: created Human21 preview with 19 resolved joints; indices 19/20 remain unresolved.")
    return group, joints


build_preview()
'''


def write_maya_preview_script_from_ir(
    bind_ir_path: str | Path,
    animation_ir_path: str | Path,
    output_path: str | Path,
    unit_scale: float = 100.0,
) -> dict[str, Any]:
    bind_ir = json.loads(Path(bind_ir_path).read_text(encoding="utf-8"))
    animation_ir = json.loads(Path(animation_ir_path).read_text(encoding="utf-8"))
    script = build_maya_preview_script(bind_ir, animation_ir, unit_scale=unit_scale)
    Path(output_path).write_text(script, encoding="utf-8")
    return {
        "output": str(output_path),
        "profile": skeleton_profile_metadata(),
        "bind_validation": validate_human21_bind_geometry(bind_ir),
    }


def write_maya_preview_script_from_raw(
    bind_raw_path: str | Path,
    animation_raw_path: str | Path,
    output_path: str | Path,
    unit_scale: float = 100.0,
) -> dict[str, Any]:
    bind_ir = build_animation_ir(bind_raw_path)
    animation_ir = build_animation_ir(animation_raw_path)
    script = build_maya_preview_script(bind_ir, animation_ir, unit_scale=unit_scale)
    Path(output_path).write_text(script, encoding="utf-8")
    return {
        "output": str(output_path),
        "profile": skeleton_profile_metadata(),
        "bind_validation": validate_human21_bind_geometry(bind_ir),
    }
